framework:
    secret: '%env(APP_SECRET)%'
    http_method_override: true
    csrf_protection: true
    session:
        handler_id: null
        cookie_secure: auto
        cookie_samesite: lax
    php_errors:
        log: true
    router:
        utf8: true
