App\Entity\Location:
    properties:
        city:
            - NotBlank: ~
            - Length:
                max: 255
        country:
            - NotBlank: ~
            - Length:
                min: 2
                max: 2
        latitude:
            - NotBlank: { groups: ['create'] }
            - Range: { min: -90, max: 90, groups: ['create', 'edit'] }
        longitude:
            - NotBlank: { groups: ['create'] }
            - Range: { min: -180, max: 180, groups: ['create', 'edit'] }

App\Entity\Measurement:
    properties:
        date:
            - NotBlank: ~
        celsius:
            - NotBlank: ~
            - Range: { min: -50, max: 50, groups: ['create', 'edit'] }
        location:
            - NotBlank: ~
